spring:
  application.name: alert-sink
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: alert-sink
      auto-offset-reset: earliest
      isolation-level: read_committed
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        string.json.add.type.headers: false

server:
  port: 8084

app:
  input: alerts
  dlt: alerts.dtl
  slackWebhook: "***Webhook***"
